# Generated by Django 5.0.3 on 2024-03-22 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_publisher',
        ),
    ]
