# Generated by Django 5.0.3 on 2024-03-28 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_tbl_quality'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_quality',
        ),
    ]
