# Generated by Django 5.0.3 on 2024-03-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_delete_tbl_quality'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_quality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_level', models.CharField(max_length=15)),
                ('quality_rule', models.CharField(max_length=50)),
                ('quality_percentage', models.CharField(max_length=15)),
            ],
        ),
    ]
