# Generated by Django 5.0.3 on 2024-03-28 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_tbl_quality'),
        ('Publisher', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_paddbook',
            name='pbook_genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_genre'),
        ),
    ]
