# Generated by Django 5.0.4 on 2024-04-07 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Publisher', '0004_alter_tbl_paddbook_pbook_genre'),
        ('User', '0015_delete_tbl_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_paddbook',
        ),
    ]
