# Generated by Django 5.0.4 on 2024-04-07 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0006_tbl_admin'),
        ('Guest', '0009_tbl_agent_tbl_publisher'),
        ('Publisher', '0005_delete_tbl_paddbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_paddbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pbook_name', models.CharField(max_length=15)),
                ('pbook_desc', models.CharField(max_length=50)),
                ('pbook_price', models.EmailField(max_length=50)),
                ('pbook_photo', models.FileField(upload_to='Assets/PublisherAddBook/')),
                ('pbook_authname', models.CharField(max_length=15)),
                ('pbook_qty', models.CharField(max_length=15)),
                ('pbook_genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_genre')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_publisher')),
            ],
        ),
    ]
