# Generated by Django 5.0.3 on 2024-03-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_publisher',
            name='user_status',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='tbl_publisher',
            name='publisher_proof',
            field=models.FileField(upload_to='Assets/UserProof/'),
        ),
    ]
