# Generated by Django 5.0.3 on 2024-03-23 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_tbl_agent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_agent',
        ),
        migrations.DeleteModel(
            name='tbl_publisher',
        ),
    ]
