# Generated by Django 5.0.3 on 2024-03-23 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0002_delete_tbl_publisher'),
        ('Guest', '0006_delete_tbl_agent_delete_tbl_publisher_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=15)),
                ('agent_contact', models.CharField(max_length=10)),
                ('agent_address', models.CharField(max_length=10)),
                ('agent_photo', models.FileField(upload_to='Assets/UserPhoto/')),
                ('agent_proof', models.FileField(upload_to='Assets/UserProof/')),
                ('agent_email', models.EmailField(max_length=50)),
                ('agent_password', models.CharField(max_length=10)),
                ('user_status', models.IntegerField(default='0')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(max_length=15)),
                ('publisher_contact', models.CharField(max_length=10)),
                ('publisher_address', models.CharField(max_length=10)),
                ('publisher_photo', models.FileField(upload_to='Assets/UserPhoto/')),
                ('publisher_proof', models.FileField(upload_to='Assets/UserProof/')),
                ('publisher_email', models.EmailField(max_length=50)),
                ('publisher_password', models.CharField(max_length=10)),
                ('user_status', models.IntegerField(default='0')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_gender', models.CharField(max_length=50)),
                ('user_contact', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=50)),
                ('user_password', models.CharField(max_length=50)),
                ('user_photo', models.FileField(upload_to='Assets/UserPhoto/')),
                ('user_proof', models.FileField(upload_to='Assets/UserProof/')),
                ('user_status', models.IntegerField(default='0')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
