# Generated by Django 5.0.4 on 2024-04-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0009_tbl_agent_tbl_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_user',
            name='user_address',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
