# Generated by Django 5.0.3 on 2024-03-28 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0005_tbl_quality'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_uaddbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubook_name', models.CharField(max_length=15)),
                ('ubook_desc', models.CharField(max_length=50)),
                ('ubook_price', models.EmailField(max_length=50)),
                ('ubook_photo', models.FileField(upload_to='Assets/UserBookPhoto/')),
                ('ubook_authname', models.CharField(max_length=15)),
                ('ubook_genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_genre')),
                ('ubook_qlty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_quality')),
            ],
        ),
    ]
