# Generated by Django 5.0.3 on 2024-04-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_swap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swap_id', models.CharField(max_length=15)),
                ('touser_id', models.CharField(max_length=15)),
                ('fromuser_id', models.CharField(max_length=15)),
                ('tobook_id', models.CharField(max_length=15)),
                ('frombook_id', models.CharField(max_length=15)),
                ('swap_status', models.CharField(max_length=15)),
                ('swap_price', models.CharField(max_length=15)),
                ('swap_paymentstatus', models.CharField(max_length=15)),
            ],
        ),
    ]
