# Generated by Django 5.0.3 on 2024-04-02 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_tbl_swap'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_swap',
        ),
    ]
