# Generated by Django 5.0.3 on 2024-04-02 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0009_tbl_agent_tbl_publisher'),
        ('User', '0003_delete_tbl_swap'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_swap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swap_id', models.CharField(max_length=15)),
                ('swap_status', models.CharField(max_length=15)),
                ('swap_price', models.CharField(max_length=15)),
                ('swap_paymentstatus', models.CharField(max_length=15)),
                ('frombook_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frombook_id', to='User.tbl_uaddbook')),
                ('fromuser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromuser_id', to='Guest.tbl_user')),
                ('tobook_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tobook_id', to='User.tbl_uaddbook')),
                ('touser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='touser_id', to='Guest.tbl_user')),
            ],
        ),
    ]
