# Generated by Django 5.0.3 on 2024-04-02 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_tbl_swap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_uaddbook',
            name='ubook_genre',
        ),
        migrations.RemoveField(
            model_name='tbl_uaddbook',
            name='ubook_qlty',
        ),
        migrations.DeleteModel(
            name='tbl_swap',
        ),
        migrations.DeleteModel(
            name='tbl_uaddbook',
        ),
    ]
