# Generated by Django 5.0.3 on 2024-04-02 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_swap',
            name='frombook_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frombook_id', to='User.tbl_uaddbook'),
        ),
    ]
