# Generated by Django 5.0.3 on 2024-04-03 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0005_tbl_quality'),
        ('Guest', '0009_tbl_agent_tbl_publisher'),
        ('User', '0008_remove_tbl_uaddbook_ubook_genre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_uaddbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubook_name', models.CharField(max_length=15)),
                ('ubook_desc', models.CharField(max_length=50)),
                ('ubook_price', models.EmailField(max_length=50)),
                ('ubook_photo', models.FileField(upload_to='Assets/UserBookPhoto/')),
                ('ubook_authname', models.CharField(max_length=15)),
                ('ubook_status', models.IntegerField(default='0')),
                ('ubook_genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_genre')),
                ('ubook_qlty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_quality')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
