# Generated by Django 5.0.3 on 2024-04-05 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0009_tbl_agent_tbl_publisher'),
        ('User', '0010_tbl_swap'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_swap',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_agent'),
        ),
    ]
