# Generated by Django 5.0.3 on 2024-04-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_tbl_swap_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_swap',
            name='swap_status',
            field=models.IntegerField(default=0),
        ),
    ]
