# Generated by Django 5.0.3 on 2024-04-06 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0009_tbl_agent_tbl_publisher'),
        ('User', '0013_tbl_booking_tbl_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_id', models.CharField(max_length=15)),
                ('complaint_title', models.CharField(max_length=50)),
                ('complaint_desc', models.CharField(max_length=100)),
                ('complaint_status', models.IntegerField(default=0)),
                ('complaint_date', models.DateField(auto_now=True)),
                ('complaint_reply', models.CharField(max_length=100, null=True)),
                ('agent_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_id', to='Guest.tbl_agent')),
                ('publisher_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publisher_id', to='Guest.tbl_publisher')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='Guest.tbl_user')),
            ],
        ),
    ]
