# Generated by Django 5.0.4 on 2024-04-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0016_tbl_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_booking',
            name='booking_amount',
            field=models.CharField(max_length=30),
        ),
    ]
