# Generated by Django 5.0.4 on 2024-04-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0018_tbl_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_swap',
            name='swap_paymentstatus',
            field=models.IntegerField(default=0),
        ),
    ]
