# Generated by Django 5.0.4 on 2024-04-08 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_tbl_admin'),
        ('Guest', '0009_tbl_agent_tbl_publisher'),
        ('User', '0019_alter_tbl_swap_swap_paymentstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_usergenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.tbl_genre')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.tbl_user')),
            ],
        ),
    ]
