# Generated by Django 5.0.4 on 2024-04-08 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0009_tbl_agent_tbl_publisher'),
        ('Publisher', '0007_alter_tbl_paddbook_pbook_price'),
        ('User', '0020_tbl_usergenre'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Publisher.tbl_paddbook')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.tbl_user')),
            ],
        ),
    ]
