# Generated by Django 5.0.4 on 2024-04-10 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0022_tbl_ubooking_tbl_ucart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_ucart',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='tbl_ucart',
            name='product',
        ),
        migrations.DeleteModel(
            name='tbl_ubooking',
        ),
        migrations.DeleteModel(
            name='tbl_ucart',
        ),
    ]
