# Generated by Django 5.0.4 on 2024-04-13 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0010_tbl_user_user_address'),
        ('User', '0026_alter_tbl_uaddbook_ubook_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_booking',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.tbl_agent'),
        ),
        migrations.AddField(
            model_name='tbl_ubooking',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.tbl_agent'),
        ),
    ]
